/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MyImagesRouteImport } from './routes/my-images'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColorImageIdRouteImport } from './routes/color/$imageId'
import { Route as ApiUploadsSplatRouteImport } from './routes/api/uploads/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MyImagesRoute = MyImagesRouteImport.update({
  id: '/my-images',
  path: '/my-images',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorImageIdRoute = ColorImageIdRouteImport.update({
  id: '/color/$imageId',
  path: '/color/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsSplatRoute = ApiUploadsSplatRouteImport.update({
  id: '/api/uploads/$',
  path: '/api/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/my-images': typeof MyImagesRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/color/$imageId': typeof ColorImageIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/my-images': typeof MyImagesRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/color/$imageId': typeof ColorImageIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/my-images': typeof MyImagesRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/color/$imageId': typeof ColorImageIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/login'
    | '/my-images'
    | '/pricing'
    | '/register'
    | '/upload'
    | '/color/$imageId'
    | '/api/auth/$'
    | '/api/uploads/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/login'
    | '/my-images'
    | '/pricing'
    | '/register'
    | '/upload'
    | '/color/$imageId'
    | '/api/auth/$'
    | '/api/uploads/$'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/login'
    | '/my-images'
    | '/pricing'
    | '/register'
    | '/upload'
    | '/color/$imageId'
    | '/api/auth/$'
    | '/api/uploads/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  MyImagesRoute: typeof MyImagesRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  UploadRoute: typeof UploadRoute
  ColorImageIdRoute: typeof ColorImageIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUploadsSplatRoute: typeof ApiUploadsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-images': {
      id: '/my-images'
      path: '/my-images'
      fullPath: '/my-images'
      preLoaderRoute: typeof MyImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color/$imageId': {
      id: '/color/$imageId'
      path: '/color/$imageId'
      fullPath: '/color/$imageId'
      preLoaderRoute: typeof ColorImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$': {
      id: '/api/uploads/$'
      path: '/api/uploads/$'
      fullPath: '/api/uploads/$'
      preLoaderRoute: typeof ApiUploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  MyImagesRoute: MyImagesRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  UploadRoute: UploadRoute,
  ColorImageIdRoute: ColorImageIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUploadsSplatRoute: ApiUploadsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
